apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejaumvoluntario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sejaumvoluntario
  template:
    metadata:
      labels:
        app: sejaumvoluntario
    spec:
      containers:
        - name: nginx
          image: harbor.local/apps/nginx:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
