apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sejaumvoluntario
spec:
  ingressClassName: nginx
  rules:
  - host: sejaumvoluntario.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sejaumvoluntario
            port:
              number: 80
